travis:
  secure:
    BINSTAR_TOKEN: lIl2WdlKdGNLLVuAD6oiNM6EG2SaYY0c4g3EaLrOUGDPtOMatWGLbSXrQUOIQGJI/yIiAypER+VMsT7pc/jC5ELy2oG1ifQMwhOcpiNhRApEUpsOV00thOgSjyBS1OHq28tcFZSJ35YZQkUzSMUTwmweQNJQHDA3IGBQBexm4WjXfTeELX8dUfEPnBmeprriQ3fwatAURB5SV4B4MixhtDtKJbi0DW19eeQ3GMqAFriSxlq+GEqHbXpDQmz3VB/GijJuTRCg2bUlK/5D5CMixLp5vtdkah8hcBg9oeQp52qaKw6N7lwGJmiFCtE3ussUUdX6eLeoofCzskztMTJ95wGGonHmXv8EEkAXQ6RxzRHzQLsl/6TbRbjp55DANyFMk4AV/mI9TkkKARXw9zp12L7yMcGXtG2W8T2KhUaBugDIgVpoKNNfHzfKGwSMUKdNVFgZvTmDCYNuTYi2oeO2Jux2kDwoBU1L1tQxAcv61arhVYo5Etyslay2W4Mj4gox/Vr78srWtQt6iji02w2rX7qLvXvrCHNBfhl9AJRlxKXM2qI6+OrRHvQzUF2kHMsaOxvCPWEZED7jCpL73p1q8H3zXe0wf5FbgAyg/rBs98g3hFN9Rw/0pNohzZahWs76nNHlQcCRlefsVwbv6P5cavIDdaak28ODcoA/rjyK1q0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
