travis:
  secure:
    BINSTAR_TOKEN: nYVqgnR68SR9fJc9CVQqc5jG4fRjzhIOvg0P1vtuOFUE98p9eXaum/C/6PWvkySle2lhHdtRKJx2aRHdrhqK6yXlse42PfaTnDuN0Sgkzc+48KSecDisz80APJjIhupjq2Uq40vxemf49sKvTJpmTz9SQHw+hdTcZsJaHRAdPUBzHxsuaz6i3qf0UCb7nn9Q8aInX5Tvm8rJm+SsYpx77zrAN7EcRfgE/z1npQm20XjMQGPU7sxYwPARMc1BpgQUck79ibVeZMLOWabodXq3PAcHkReYuh1iI3Z2kuyRi+18aVbYTDMOkt0BRUG1D3RFysGSEDfFJySnZgr0agZttUFUjGOBTyrrqna95COal2Fbnwst3DsyaeNR/JLI9sOB4vEo9VlzQvWvCtWDktxZlrOJ5Eur9AHCRPFl8pXAZiMvtEAdFPeHf3SZeJ28QDGagRMv8wIsVfynR6+Jug9Tb2+kHSmNZU5BT2tRtfwIFRwjoXsaJHx7QDyHucqFbeWtUGI6u8l+debcNI6l60s+V43ENUxsj0Sks5oBSGmODLhq85Pc0YGCRJgbw4j2RmCP919gnhp1VacxuqTwNdnDU5wbeV9J16hbcDUpvhNzYN4cNzh1O6MNpcESsv6e/Azv34a4Ce00z2PGW0kkIaN/IDoS0kB7+uQCWvKm9pGZkLE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
