travis:
  secure:
    BINSTAR_TOKEN: ZILs1JLl5cAtHJ2HMVVB0pS4qjJm+yefl1OZGBpkKa+d3gnhKtbw9wVFzl5nOtME5+YQAR/8/lN/QVV3P8vztNoz3PdGOGCAHu6mqvc81j/x7CTpkYFl3kmHuIg1PxOFUuntObu80TQaZWiT7JEuOc8aSIv4grVAlp12+R9eZKKan2UJoCiXvcxNc/WRpQpjLDExaE16PYCOJi31GSpDzGD1vjT4nst3y3oLVigTOLsGkDOdG59xjK9KR38Xtb8OVZXSpuJNT0W233VomGtL6plbdlW/jUQV0TCb2/a8spiVUoeeWuhH9BpZe1L4Nd0br6MgKzIPzsOBPVHnc0KGr32JxJ3FAHtUWESVqKWWz8STVcPZflnLE8/TncZCwIbVD1j02EL2PbU062pJRDL7ClCQ35CxjHz910gWylPjjOTv/RvbETIILHEJ+/Cvf5fhpDqzblb7kNUyAYGx84KJycGZDsYIqW8WbqCIxSiUizUd738ZNy85sfpvh/3sUrNDRbjqZ9FN0epNQd3xkhCzKWKglJBllHsw3JwO0WP6JzIVIR9/6VvpfTgD24wEm0AWIMaMtp8DTBl1DntxfUWQvEFkwEk+ehbaA7jw5OXIN92143x/nklOPtezG8rAuD8QwE8SrqABTCHO/aw2e3+WpreDgve/jNrbBEJOi8FST9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
