travis:
  secure:
    BINSTAR_TOKEN: ZrqGipaiI+9piYAPMYnpPmXnvfAjacJwygKb5I2NbJ3WfTscG8k83USs0nwU3TcwG2qdEZW7AvmfwPfbkH8tAjk7nD8FdxeCzNs/CpVOBNIz9+7wAs4FwskGixtucc/aHVrmx93BpbX4jqXyoCmbD9+M/dXC1HNghhkvCI4WUcG8FII5xs6c364uBYcjc+f/dzahXh2s97LSM4TpdmAzZGO3D3cd/qG6jjZ+mnmICqVtLQH5GAyvdxuRVm4LijG9T6zzeJR+iLZZ3V4NsCyC4CfXl/zmCIcnDpVWutaL4kG1NSp3SNoejKCzEeUpBUsl8m0Fdqjv0reI3wOPZMTvdSxSMBjXd+CoNziB3W2fAoPQDR6PNPvhv7ZM1V6idbNVylsUVUPT6LW8nxn88b4TnKfA1OXoI7DEW1zw2O54VFDphudAap1yy3GZ4y8OidJ/JCDYg2rCvBSAiAqg7mzf+P47kHMsfvYqkanvP/gYDSoJvajYxML5GunX+QiwEeJ6bjbIvMAWsQN5ytPCp07GcTn4YAHUCKZkCgBgL360haORX7MowTFEZTglFp/1LO10UuPZ5aBFqesH7skOPvW/c92nkdalVmaHWKz5Qu8Oqh7ZuUb/VrajBAPF3ltFdKJgZT12/kX56bZn3/uelydvn+tL1WhaEuSeOXAGsCnHoFk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
