travis:
  secure:
    BINSTAR_TOKEN: DFNtYZKmsn64L/p3ap5I0/mC8ituXfhJh3Z1esownMscMfPYDfGuzq/BWBqXl4B2FRksb23uXlZyQxu4L2oG3eJw1SCjwswUxiY6WcPFInP2McB4cHpY1SEoJL9YT+/zBkkqNf8Wew6iAomudPpx4kh4YXa38RANXKiu9oYxcDmUq7rCTByfNINCrFLHZkPD28tzrFOCgFnM6B/mjN6vl5Rw8DY17QDwar4jeP001y+7nUGfRnQou8AicxCv9KtNwr4Dd19uRcHv7Qwf6JngQSkyA6Rd4s9AAcS2J3UKxDTg3shb6WdUSCJVV7hNzm7ruTZ647BUMgV5D+Qy6mOoPJODMGRnNCV2P6PJBxuKZnLsXibpuCypyMDG5gAPmpEzwZ4r/x7NpvhTQFAZ6MplfS60olfonRo66PWDRhILQWkkVa0Lfbu2YMhu4e7Kyb5OmNn9UpJeRGkIs64i305E4P/u3kscmJrpWO08fe4kWHe3HMy4gtAubGaTHrS8ffzQUOhXR1dlVtDdp32Tarj7yY55ieHRh/6xC5XjuLoxer9a0o7uzlLzNZVxk1hOTAqt8mCD+zjhvexKkU/yu7c7tGrOY+niHdUKqMFIEtLkQetQVs2t4/fRPYztVpiOFxTFe2unKgANiN6K3i2CIQ+e7bimRjZ30qTzJLBsjaPRy/E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
